FROM golang:1.17-alpine
MAINTAINER CyberArk Software Ltd.
LABEL id="conjur-authn-k8s-client-test-runner"

ENTRYPOINT [ "go", "test", "-v", "-timeout", "3m" ]
WORKDIR /conjur-authn-k8s-client

RUN apk add -u curl \
               gcc \
               git \
               mercurial \
               musl-dev

COPY go.mod go.sum /conjur-authn-k8s-client/

# Use latest dependency for automated release process
RUN go get github.com/cyberark/conjur-opentelemetry-tracer@latest
RUN go mod download

COPY . .
# Add required cyberark/conjur-opentelemetry-tracer package to go.mod
RUN go mod tidy
