FROM golang:1.15-alpine
MAINTAINER CyberArk Software Ltd.
LABEL id="conjur-authn-k8s-client-junit-processor"

WORKDIR /test

RUN apk add -u curl \
               gcc \
               git \
               mercurial \
               musl-dev \
               bash

RUN go get -u github.com/jstemmer/go-junit-report
