# =================== CONTAINER FOR HELM UNIT TEST ===================

FROM golang:1.24-alpine AS conjur-k8s-helm-unit-test

# Install packages for installing Helm and Helm unittest plugin
RUN apk add --no-cache bash bind-tools coreutils curl git ncurses openssl

# Install helm
RUN curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

# Install helm unittest plugin. The latest version, v0.3.1, fails tests
# that render with the $.Files.Get template function, which is used by
# the Cluster Prep Helm chart.
# https://github.com/helm-unittest/helm-unittest/issues/135
#
# Pinning helm-unittest to v0.2.11 until this is fixed.
RUN mv /etc/os-release /etc/os-release.bak && \
    touch /etc/os-release && \
    helm plugin install https://github.com/helm-unittest/helm-unittest --version 0.2.11 && \
    mv /etc/os-release.bak /etc/os-release

# Install yq
# Build from source to get the latest version due to CVE-2022-4172, CVE-2024-34156
ARG YQ_VERSION=v4

RUN git clone --branch $YQ_VERSION https://github.com/mikefarah/yq /yq && \
    cd /yq && \
    # Update golang.org/x/net to v0.37.0 to resolve CVE-2025-22870
    go get golang.org/x/net@v0.37.0 && \
    go mod tidy && \
    go build && \
    mv yq /usr/bin/yq && \
    rm -rf /yq && \
    chmod +x /usr/bin/yq

RUN mkdir -p /conjur-authn-k8s-client
WORKDIR /conjur-authn-k8s-client

# Workaround for CVE-2022-24765 when running git inside a docker container
RUN git config --global --add safe.directory /conjur-authn-k8s-client

LABEL name="conjur-k8s-helm-unit-test"
LABEL vendor="CyberArk"
LABEL version="$VERSION"
LABEL release="$VERSION"
LABEL summary="Conjur Kubernetes test image for running Helm unit tests"
LABEL description="The Conjur test image that is used for Helm unit testing"

COPY . .

ENTRYPOINT ["/conjur-authn-k8s-client/bin/test-helm-unit"]
