FROM golang:1.15-alpine
MAINTAINER CyberArk Software Ltd.
LABEL id="conjur-authn-k8s-client-test-runner"

ENTRYPOINT [ "go", "test", "-v", "-timeout", "3m" ]
WORKDIR /conjur-authn-k8s-client

RUN apk add -u curl \
               gcc \
               git \
               mercurial \
               musl-dev

COPY go.mod go.sum /conjur-authn-k8s-client/

RUN go mod download

COPY . .
