#!/bin/bash

source ../common/utils.sh

banner $BOLD "Running Helm lint for chart \"conjur-config-namespace-prep\""
helm lint . \
    --set authnK8s.goldenConfigMap="authn-k8s-configmap" \
    --set authnK8s.namespace="app-test" \
    --set authnK8s.backendSecretToCreate="test-backend-secret" \
    --set authnK8s.backendCertificateFilePath="files/ca.pem"
    --set authnK8s.backendKeyFilePath="files/ca-key.pem"
    --set test.mock.enable=true
