apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.authnK8s.backendSecret }}
  labels: 
    app.kubernetes.io/name: {{ .Values.authnK8s.backendSecret }}
    app.kubernetes.io/component: authn-k8s-{{ .Values.authnK8s.backendSecret }}
    app.kubernetes.io/instance: {{ .Release.Namespace }}
    app.kubernetes.io/part-of: authn-k8s-namespace-config
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
data:
  server.crt: {{ .Files.Get "files/ca.pem" | b64enc }}
  server.key: {{ .Files.Get "files/ca-key.pem" | b64enc }}
