{{- if .Values.authnRoleBinding.create -}}
# The Authenticator RoleBinding grants permissions to the Conjur Authenticator ServiceAccount
# for the authenticator ClusterRole, which provides a list of Kubernetes API access permissions.
# This is required to validate application identities.
{{ $config := required "Both authnK8s.namespace and authnK8s.configMap are required" .Values.authnK8s -}}

{{ $g := .Values.test.mock -}}
{{ if not .Values.test.mock.enable -}}
{{ $g = (lookup "v1" "ConfigMap" .Values.authnK8s.namespace .Values.authnK8s.goldenConfigMap).data -}}
{{ end -}}

apiVersion: {{ include "conjur-prep.rbac-api" . }}
kind: RoleBinding
metadata:
  name: {{ .Values.authnRoleBinding.name }}
  labels:
    app.kubernetes.io/name: "conjur-rolebinding"
    app.kubernetes.io/component: "conjur-namespace-access"
    app.kubernetes.io/instance: "conjur-{{ .Release.Namespace }}-rolebinding"
    app.kubernetes.io/part-of: "conjur-config"
    conjur.org/name: "conjur-rolebinding"
subjects:
- kind: ServiceAccount
  name: {{ get $g "authnK8sServiceAccount" }}
  namespace: {{ .Values.authnK8s.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ get $g "authnK8sClusterRole" }}
{{- end }}
