# Default values for the Application with Secretless sidecar Helm chart
# This is a YAML-formatted file

global:
  conjur:
    # name of the ConfigMap created by the conjur-config-namespace-prep chart
    conjurConnConfigMap: "conjur-connect"
  appServiceType: "NodePort"

app:
  image:
    repository: "cyberark/demo-app"
    tag: "latest"
    # supported values: "Always", "IfNotPresent", "Never"
    pullPolicy: "Always"
  platform: "kubernetes"

secretless:
  image:
    repository: "cyberark/secretless-broker"
    tag: "latest"
    # supported values: "Always", "IfNotPresent", "Never"
    pullPolicy: "Always"

conjur:
  authnConfigMap:
    create: true
    name: "conjur-authn-configmap"
  authnLogin: ""
