---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: test-app-conjur-authenticator-role-binding-{{ CONJUR_NAMESPACE_NAME }}
  namespace: {{ TEST_APP_NAMESPACE_NAME }}
subjects:
  - kind: ServiceAccount
    name: {{ CONJUR_SERVICE_ACCOUNT }}
    namespace: {{ CONJUR_NAMESPACE_NAME }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ CONJUR_AUTHN_CLUSTER_ROLE }}
