---
kind: Service
apiVersion: v1
metadata:
  name: test-summon-init-app-backend
  namespace: {{ TEST_APP_NAMESPACE_NAME }}
spec:
  selector:
    app: test-summon-init-app-backend
  ports:
    - port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: summon-init-pg
  labels:
    app: test-summon-init-app-backend
spec:
  serviceName: test-summon-init-app-backend
  selector:
    matchLabels:
      app: test-summon-init-app-backend
  template:
    metadata:
      labels:
        app: test-summon-init-app-backend
    spec:
      containers:
      - name: test-summon-init-app-backend
        image: centos/postgresql-95-centos7
        imagePullPolicy: Always
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRESQL_USER
            value: test_app
          - name: POSTGRESQL_PASSWORD
            value: {{ TEST_APP_DB_PASSWORD }}
          - name: POSTGRESQL_DATABASE
            value: test_app
        volumeMounts:
          - name: backend-certs
            mountPath: "/etc/certs/"
            readOnly: true
        command: ["/bin/sh", "-c"]
        args:
          - mkdir -p /opt/app-root/certs/;
            install -m 0600 /etc/certs/* /opt/app-root/certs;
            run-postgresql -c ssl=on -c ssl_cert_file=/opt/app-root/certs/server.crt -c ssl_key_file=/opt/app-root/certs/server.key
      volumes:
      - name: backend-certs
        secret:
          secretName: test-app-backend-certs

---
kind: Service
apiVersion: v1
metadata:
  name: test-summon-sidecar-app-backend
  namespace: {{ TEST_APP_NAMESPACE_NAME }}
spec:
  selector:
    app: test-summon-sidecar-app-backend
  ports:
    - port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: summon-sidecar-pg
  labels:
    app: test-summon-sidecar-app-backend
spec:
  serviceName: test-summon-sidecar-app-backend
  selector:
    matchLabels:
      app: test-summon-sidecar-app-backend
  template:
    metadata:
      labels:
        app: test-summon-sidecar-app-backend
    spec:
      containers:
      - name: test-summon-sidecar-app-backend
        image: centos/postgresql-95-centos7
        imagePullPolicy: Always
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRESQL_USER
            value: test_app
          - name: POSTGRESQL_PASSWORD
            value: {{ TEST_APP_DB_PASSWORD }}
          - name: POSTGRESQL_DATABASE
            value: test_app
        volumeMounts:
        - name: backend-certs
          mountPath: "/etc/certs/"
          readOnly: true
        command: ["/bin/sh", "-c"]
        args:
          - mkdir -p /opt/app-root/certs/;
            install -m 0600 /etc/certs/* /opt/app-root/certs;
            run-postgresql -c ssl=on -c ssl_cert_file=/opt/app-root/certs/server.crt -c ssl_key_file=/opt/app-root/certs/server.key
      volumes:
      - name: backend-certs
        secret:
          secretName: test-app-backend-certs

---
kind: Service
apiVersion: v1
metadata:
  name: test-secretless-app-backend
  namespace: {{ TEST_APP_NAMESPACE_NAME }}
spec:
  selector:
    app: test-secretless-app-backend
  ports:
    - port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: secretless-pg
  labels:
    app: test-secretless-app-backend
spec:
  serviceName: test-secretless-app-backend
  selector:
    matchLabels:
      app: test-secretless-app-backend
  template:
    metadata:
      labels:
        app: test-secretless-app-backend
    spec:
      containers:
      - name: test-secretless-app-backend
        image: centos/postgresql-95-centos7
        imagePullPolicy: Always
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRESQL_USER
            value: test_app
          - name: POSTGRESQL_PASSWORD
            value: {{ TEST_APP_DB_PASSWORD }}
          - name: POSTGRESQL_DATABASE
            value: test_app
        volumeMounts:
        - name: backend-certs
          mountPath: "/etc/certs/"
          readOnly: true
        command: ["/bin/sh", "-c"]
        args:
          - mkdir -p /opt/app-root/certs/;
            install -m 0600 /etc/certs/* /opt/app-root/certs;
            run-postgresql -c ssl=on -c ssl_cert_file=/opt/app-root/certs/server.crt -c ssl_key_file=/opt/app-root/certs/server.key
      volumes:
      - name: backend-certs
        secret:
          secretName: test-app-backend-certs
