---
apiVersion: v1
kind: Pod
metadata:
  name: test-curl
  labels:
    name: test-curl
spec:
  containers:
  - name: busyboxplus
    image: radial/busyboxplus:curl
    imagePullPolicy: Always
    command: ["sh", "-c", "tail -f /dev/null"]
