---
apiVersion: v1
kind: Service
metadata:
  name: test-app-secretless
  labels:
    app: test-app-secretless
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: test-app-secretless
  type: {{ SERVICE_TYPE }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oc-test-app-secretless
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: test-app-secretless
  name: test-app-secretless
spec:
  replicas: 1
  selector:
    app: test-app-secretless
  template:
    metadata:
      labels:
        app: test-app-secretless
    spec:
      serviceAccountName: oc-test-app-secretless
      containers:
      - image: cyberark/demo-app
        imagePullPolicy: Always
        name: test-app-secretless
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /pets
            port: http
          initialDelaySeconds: 15
          timeoutSeconds: 5
        env:
          - name: DB_URL
            value: {{ SECRETLESS_DB_URL }}
      - image: {{ SECRETLESS_IMAGE }}
        imagePullPolicy: Always
        name: secretless
        args: ["-f", "/etc/secretless/secretless.yml"]
        ports:
        - containerPort: 5432
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: CONJUR_AUTHN_URL
            value: "{{ CONJUR_AUTHN_URL }}"
          - name: CONJUR_APPLIANCE_URL
            value: "{{ CONJUR_APPLIANCE_URL }}"
          - name: CONJUR_ACCOUNT
            value: "{{ CONJUR_ACCOUNT }}"
          - name: CONJUR_AUTHN_LOGIN
            value: "{{ CONJUR_AUTHN_LOGIN_PREFIX }}/oc-test-app-secretless"
          - name: CONJUR_SSL_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                name: "{{ CONFIG_MAP_NAME }}"
                key: ssl-certificate
        volumeMounts:
        - name: config
          mountPath: "/etc/secretless"
          readOnly: true
      imagePullSecrets:
        - name: dockerpullsecret
      volumes:
      - name: config
        configMap:
          name: test-app-secretless-config
