apiVersion: v1
kind: Secret
metadata:
  name: test-app-secrets-provider-init-secret
type: Opaque
stringData:
  conjur-map: |-
    DB_URL: test-secrets-provider-init-app-db/url
    DB_USERNAME: test-secrets-provider-init-app-db/username
    DB_PASSWORD: test-secrets-provider-init-app-db/password
    OTHER_URL: my-app-db/prod/url
    OTHER_USERNAME: my-app-db/prod/username
    OTHER_PASSWORD: my-app-db/prod/password
