# Default values for the Application Namespace Prep Helm chart
# This is a YAML-formatted file.

app:
  image:
    repository: "localhost:5000/test-sidecar-app"
    tag: "conjur-oss"
    # supported values: "Always", "IfNotPresent", "Never"
    pullPolicy: "Always"
 
authnClient:
  image:
    repository: "cyberark/conjur-authn-k8s-client"
    tag: "latest"
    # supported values: "Always", "IfNotPresent", "Never"
    pullPolicy: "Always"

conjur:
  authnConfigMap:
    create: true
    name: "conjur-authn-configmap"
  # host/conjur/authn-k8s/<authenticator-ID>/<conjur-policy-layer-or-group>/<app-host-id>
  authnLogin:
