apiVersion: v1
kind: ConfigMap
metadata:
    name: secrets-configmap
    labels:
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
      conjur.org/name: "secrets-configmap"
      helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
    secrets.yml: |
      DB_URL: !var test-summon-sidecar-app-db/url
      DB_USERNAME: !var test-summon-sidecar-app-db/username
      DB_PASSWORD: !var test-summon-sidecar-app-db/password
