{{- if .Values.authnK8s.clusterRole.create }}
# This ClusterRole defines the Kubernetes API access permissions that the Conjur
# authenticator will require in order to validate application identities.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.authnK8s.clusterRole.name | default "conjur-clusterrole" }}
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/name: "conjur-clusterrole"
    app.kubernetes.io/component: "conjur-permissions"
    app.kubernetes.io/instance: "conjur-clusterrole"
    app.kubernetes.io/part-of: "conjur-config"
    conjur.org/name: "conjur-clusterrole"
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}

rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "serviceaccounts"]
  verbs: ["get", "list"]
- apiGroups: ["extensions"]
  resources: [ "deployments", "replicasets"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: [ "deployments", "statefulsets", "replicasets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create", "get"]
{{- end }}
