# Default values for the Application with Secrets Provider init container in Push-to-File mode Helm chart
# This is a YAML-formatted file.

global:
  conjur:
    # name of the ConfigMap created by the conjur-config-namespace-prep chart
    conjurConnConfigMap: "conjur-connect"
  appServiceType: "NodePort"

app:
  image:
    repository: "docker.io/cyberark/demo-app"
    tag: "latest"
    # supported values: "Always", "IfNotPresent", "Never"
    pullPolicy: "Always"
  platform: "kubernetes"
  secretsMountPath: "/mounted/secrets"

secretsProvider:
  image:
    repository: "docker.io/cyberark/secrets-provider-for-k8s"
    tag: "latest"
    # supported values: "Always", "IfNotPresent", "Never"
    pullPolicy: "Always"

conjur:
  authnLogin: ""
