apiVersion: v1
kind: Service
metadata:
  name: test-app-secrets-provider-p2f
  labels:
    app: test-app-secrets-provider-p2f
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: test-app-secrets-provider-p2f
  type: {{ .Values.global.appServiceType }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-app-secrets-provider-p2f
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-app-secrets-provider-p2f
  name: test-app-secrets-provider-p2f
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app-secrets-provider-p2f
  template:
    metadata:
      labels:
        app: test-app-secrets-provider-p2f
      annotations:
        conjur.org/container-mode: "init"
        conjur.org/debug-logging: "true"
        conjur.org/authn-identity: {{ quote .Values.conjur.authnLogin }}
        conjur.org/secrets-destination: "file"
        conjur.org/secrets-refresh-interval: 2s
        conjur.org/restart-app-signal: SIGKILL
        conjur.org/conjur-secrets.p2f-app: |
          - test-secrets-provider-p2f-app-db/url
          - test-secrets-provider-p2f-app-db/username
          - test-secrets-provider-p2f-app-db/password
        conjur.org/secret-file-path.p2f-app: "./application.yaml"
        conjur.org/secret-file-format.p2f-app: template
        conjur.org/secret-file-template.p2f-app: |
          spring:
            datasource:
              platform: postgres
              url: jdbc:{{ printf `{{ secret "url" }}` }}
              username: {{ printf `{{ secret "username" }}` }}
              password: {{ printf `{{ secret "password" }}` }}
            jpa:
              generate-ddl: true
              hibernate:
                ddl-auto: update
        conjur.org/conjur-secrets.db: |
          - db-url: my-app-db/prod/url
          - db-username: my-app-db/prod/username
          - db-password: my-app-db/prod/password
        conjur.org/secret-file-format.db: yaml
        conjur.org/jaeger-collector-url: http://jaeger-collector.jaeger.svc.cluster.local/api/traces
    spec:
      serviceAccountName: test-app-secrets-provider-p2f
      shareProcessNamespace: true
      containers:
      - image: {{ printf "%s:%s" .Values.app.image.repository .Values.app.image.tag }}
        imagePullPolicy: {{ .Values.app.image.pullPolicy }}
        name: test-app
        command: [ "java", "-jar", "/app.jar", {{ printf "--spring.config.location=file:%s/application.yaml" .Values.app.secretsMountPath }} ]
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /pets
            port: http
          initialDelaySeconds: 15
          timeoutSeconds: 5
        volumeMounts:
        - name: secrets
          mountPath: {{ .Values.app.secretsMountPath }}
      - image: secrets-provider-for-k8s:secrets-rotation
        imagePullPolicy: Never
        name: cyberark-secrets-provider-for-k8s
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        envFrom:
        - configMapRef:
            name: {{ .Values.global.conjur.conjurConnConfigMap }}
        volumeMounts:
        - name: conjur-access-token
          mountPath: /run/conjur
        - name: conjur-certs
          mountPath: /etc/conjur/ssl
        - name: podinfo
          mountPath: /conjur/podinfo
        - name: secrets
          mountPath: /conjur/secrets
        securityContext:
          capabilities:
            add:
            - SYS_PTRACE
      - name: shell-2
        image: busybox
        command: ["sleep", "infinity"]
        securityContext:
          runAsGroup: 0
          runAsUser: 12345
      {{- if eq .Values.app.platform "kubernetes" }}
      imagePullSecrets:
        - name: dockerpullsecret
      securityContext:
        fsGroup: 0
        runAsGroup: 0
        runAsUser: 65534
      {{- end }}
      volumes:
      - name: conjur-access-token
        emptyDir:
          medium: Memory
      - name: conjur-certs
        emptyDir:
          medium: Memory
      - name: podinfo
        downwardAPI:
          items:
          - path: annotations
            fieldRef:
              fieldPath: metadata.annotations
      - name: secrets
        emptyDir:
          medium: Memory
