apiVersion: v1
kind: ConfigMap
metadata:
  name: secretless-config-configmap
  labels:
    app: test-app-secretless-broker
data:
  secretless_config.yaml: |-
{{ .Files.Get "secretless_config.yaml" | indent 4 }}
