name: Upload Release Artifacts

on:
  # Run this on tagged releases
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Package release artifacts
        run: bin/package-release-artifacts.sh

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: helm/artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
