version: "2"
services:
  test-app-pg:
    protocol: pg
    listenOn: tcp://0.0.0.0:5432
    credentials:
      host:
        from: conjur
        get: test-secretless-app-db/host
      port:
        from: conjur
        get: test-secretless-app-db/port
      username:
        from: conjur
        get: test-secretless-app-db/username
      password:
        from: conjur
        get: test-secretless-app-db/password
      sslmode: disable
